pages:
  stage: deploy
  image: node:16-alpine3.16
  environment: production
  script:
    - npm install
    - npm run build-storybook
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
